AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - config/unicorn*.rb
Lint/HandleExceptions:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false