language: ruby
install:
  - time gem install bundler # use the very latest Bundler
  - travis_retry bundle install
  - bundle clean # delete now-outdated gems
cache: bundler

rvm:
  - 2.1.1

env:
  - RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec spec