language: ruby
install:
  - time gem install pry-rails -v '0.3.2'
 
cache: bundler

rvm:
  - 2.1.1

env:
  - RAILS_ENV=test
before_script:
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec spec